In [21]:
import pandas as pd
'''Загрузим данные по населению г. Москва'''
people = pd.read_csv("https://video.ittensive.com/python-advanced/data-9753-2019-07-25.utf.csv", delimiter=";")
people = people.set_index(["Year", "Period"])#Укажим индекс на  две колонки
print (people.head())# Посмотрим из чего сотоит набор этих данных
MCHS = pd.read_csv("https://video.ittensive.com/python-advanced/data-5283-2019-10-04.utf.csv", delimiter=";")
'''Загрузим данные по вызовам пожарной службы'''
MCHS = MCHS.set_index(["AdmArea", "Year", "Month"])#Укажим индекс на  три колонки
print (MCHS.head())
MCHS = MCHS.loc["Центральный административный округ"]#Используем только те данные которые относятся к "Центральный административный округ"
MCHS.index.names = ["Year", "Period"]#Перенаименуем столбец для дальнейшего объединения двух фреймов данных
print (MCHS.head())
data = pd.merge(people, MCHS, left_index=True, right_index=True)#Объеденим данные
data = data.reset_index()#сбросим индекс
data = data.set_index("Calls")#Переназначим индекс на звонки
'''Отсортируем полученные данные и выведем минимальное(первое) значение'''
data = data.sort_index()
print (data)
'''Теперь получим данные по минимальному количеству вызовов и соответствюющее ему количество безработных'''
print (data["UnemployedMen"][0:1])

              global_id  ID  UnemployedMen  UnemployedWomen  UnemployedYoung
Year Period
2001 Декабрь   39809862   1           8896            25762             6696  \
2003 Декабрь   64592413   3           8679            24967             6226
2004 Декабрь   64592414   4           9822            25239             7318
2005 Декабрь   64592415   5          10844            23597             6890
2006 Декабрь   64592416   6          11041            22928             6604

              UnemployedDisabled  UnemployedTotal  Unnamed: 9
Year Period
2001 Декабрь                 824            34658         NaN
2003 Декабрь                1155            33646         NaN
2004 Декабрь                1411            35061         NaN
2005 Декабрь                1531            34441         NaN
2006 Декабрь                1671            33969         NaN
                                                     ID  global_id  Calls
AdmArea                                 Year Month
Центральный административный округ      2015 Январь   1   37153160    408  \
Северный административный округ         2015 Январь   2   37153161    408
Северо-Восточный административный округ 2015 Январь   3   37153162    445
Восточный административный округ        2015 Январь   4   37153163    619
Юго-Восточный административный округ    2015 Январь   5   37153164    541

                                                     Unnamed: 6
AdmArea                                 Year Month
Центральный административный округ      2015 Январь         NaN
Северный административный округ         2015 Январь         NaN
Северо-Восточный административный округ 2015 Январь         NaN
Восточный административный округ        2015 Январь         NaN
Юго-Восточный административный округ    2015 Январь         NaN
              ID  global_id  Calls  Unnamed: 6
Year Period
2015 Январь    1   37153160    408         NaN
     Февраль  12   37153172    220         NaN
     Март     23   37153183    533         NaN
     Апрель   34   37153194    568         NaN
     Май      45   37153205    303         NaN
       Year    Period  global_id_x  ID_x  UnemployedMen  UnemployedWomen
Calls
220    2015   Февраль    273573614    52          13465            18080  \
303    2015       Май    273573617    55          14873            19407
350    2015    Ноябрь    273573623    61          16688            22881
353    2016   Февраль    273573627    65          19819            25758
355    2017   Февраль    338496741    77          15459            19364
359    2015   Декабрь    273573624    62          18615            25431
375    2017      Март    338497586    78          15155            18478
378    2019    Январь    918869065   100          12225            16078
385    2015    Август    273573620    58          15232            19966
387    2016      Июнь    273573631    69          19624            24086
389    2016    Январь    273573626    64          18477            25062
392    2016   Декабрь    282746341    75          16054            20833
395    2016   Октябрь    281593353    73          16242            21151
396    2015      Июнь    273573618    56          14935            19782
396    2017    Ноябрь    841752797    86          12054            15554
400    2015  Сентябрь    273573621    59          15321            20687
402    2015   Октябрь    273573622    60          15730            21556
408    2015    Январь    273573613    51          12233            17039
408    2016      Март    273573628    66          20501            25725
410    2016    Апрель    273573629    67          21035            25736
414    2015      Июль    273573619    57          15208            19910
419    2017    Январь    323476240    76          15253            20006
420    2016       Май    273573630    68          20283            24839
427    2016      Июль    273573632    70          18727            23132
439    2017    Апрель    419018595    79          14703            17885
444    2017      Июль    638722421    82          12902            15983
446    2017    Август    671788231    83          12498            15489
458    2017       Май    476885649    80          13696            16874
465    2018    Январь    843989666    88          12782            16809
478    2017  Сентябрь    671793397    84          12129            15554
479    2017      Июнь    615575599    81          13169            16231
480    2017   Октябрь    671801829    85          11971            15446
490    2019      Март    918869067   102          13433            17164
496    2018      Июль    886051152    94          10869            13881
512    2018    Август    886440501    95          10745            13837
515    2018   Февраль    858378159    89          12993            16603
521    2018   Декабрь    909303094    99          12063            15815
523    2018   Октябрь    896740236    97          10763            14375
525    2019      Июнь    933200260   105          12260            15769
533    2018  Сентябрь    894075540    96          10651            14043
533    2015      Март    273573615    53          14253            18681
540    2018    Ноябрь    904345746    98          11080            14610
544    2018      Март    861113574    90          12793            16301
554    2019       Май    933200250   104          12818            16221
559    2019    Апрель    926094627   103          13803            17319
568    2015    Апрель    273573616    54          15159            19859
603    2019   Февраль    918869066   101          13123            16904
607    2018       Май    880655734    92          11622            15020
608    2017   Декабрь    841752805    87          12971            17109
619    2018      Июнь    880655751    93          11149            14341
654    2018    Апрель    863485150    91          12527            15988

       UnemployedYoung  UnemployedDisabled  UnemployedTotal  Unnamed: 9  ID_y
Calls
220               4645                1028            31545         NaN    12  \
303               5131                1042            34280         NaN    45
350               6108                1055            39569         NaN   111
353               6859                1335            45577         NaN   144
355               4511                 980            34823         NaN   276
359               6817                1128            44046         NaN   122
375               4365                 927            33633         NaN   287
378               2960                 533            28303         NaN   529
385               5312                 996            35198         NaN    78
387               6066                1196            43710         NaN   188
389               6368                1364            43539         NaN   133
392               4794                1075            36887         NaN   254
395               4969                1104            37393         NaN   232
396               5140                 969            34717         NaN    56
396               3438                 714            27608         NaN   375
400               5649                 956            36008         NaN    89
402               5829                1020            37286         NaN   100
408               4106                1001            29272         NaN     1
408               6847                1330            46226         NaN   155
410               6900                1281            46771         NaN   166
414               5162                 986            35118         NaN    67
419               4505                1007            35259         NaN   265
420               6433                1237            45122         NaN   177
427               5732                1188            41859         NaN   199
439               4113                 869            32588         NaN   298
444               3545                 756            28885         NaN   331
446               3571                 738            27987         NaN   342
458               3726                 797            30570         NaN   309
465               3537                 708            29591         NaN   397
478               3557                 722            27683         NaN   353
479               3484                 776            29400         NaN   320
480               3512                 736            27417         NaN   364
490               3102                 593            30597         NaN   551
496               2637                 501            24750         NaN   463
512               2735                 503            24582         NaN   474
515               3442                 658            29596         NaN   408
521               3077                 527            27878         NaN   518
523               2892                 477            25138         NaN   496
525               2545                 576            28029         NaN   584
533               2829                 472            24694         NaN   485
533               5072                1014            32934         NaN    23
540               2911                 467            25690         NaN   507
544               3309                 638            29094         NaN   419
554               2711                 577            29039         NaN   573
559               3060                 593            31122         NaN   562
568               5385                1052            35018         NaN    34
603               3103                 575            30027         NaN   540
607               2816                 575            26642         NaN   441
608               3676                 722            30080         NaN   386
619               2639                 526            25490         NaN   452
654               3188                 599            28515         NaN   430

       global_id_y  Unnamed: 6
Calls
220       37153172         NaN
303       37153205         NaN
350       59487900         NaN
353       64364589         NaN
355      323477492         NaN
359       62435324         NaN
375      334978972         NaN
378      909726385         NaN
385       37153238         NaN
387      171572047         NaN
389       64187470         NaN
392      282670884         NaN
395      279239447         NaN
396       37153216         NaN
396      689078837         NaN
400       37153249         NaN
402       37153260         NaN
408       37153160         NaN
408      167615194         NaN
410      169251943         NaN
414       37153227         NaN
419      284507333         NaN
420      170688968         NaN
427      171729187         NaN
439      400641872         NaN
444      620713785         NaN
446      638742420         NaN
458      423648124         NaN
465      839524114         NaN
478      642001699         NaN
479      477689488         NaN
480      662208077         NaN
490      916266288         NaN
496      881172894         NaN
512      886303993         NaN
515      853996670         NaN
521      905410016         NaN
523      895977804         NaN
525      930769929         NaN
533      889767255         NaN
533       37153183         NaN
540      901533082         NaN
544      860314884         NaN
554      926245039         NaN
559      919904931         NaN
568       37153194         NaN
603      912314863         NaN
607      864432139         NaN
608      831948203         NaN
619      872868381         NaN
654      862003768         NaN
Calls
220    13465
Name: UnemployedMen, dtype: int64

In [20]:
import pandas as pd
people = pd.read_csv("https://video.ittensive.com/python-advanced/data-9753-2019-07-25.utf.csv", delimiter=";")
people = people.set_index(["Year", "Period"])
MCHS = pd.read_csv("https://video.ittensive.com/python-advanced/data-5283-2019-10-04.utf.csv", delimiter=";")
MCHS = MCHS.set_index(["AdmArea", "Year", "Month"])
MCHS = MCHS.loc["Центральный административный округ"]
MCHS.index.names = ["Year", "Period"]
data = pd.merge(people, MCHS, left_index=True, right_index=True)
data = data.reset_index()
data = data.set_index("Calls")
data = data.sort_index()
print (data["UnemployedMen"][0:1])

Calls
220    13465
Name: UnemployedMen, dtype: int64